### ISSUE TITLE
youtube-tracker / Cannot call method "split" of undefined.

### ISSUE THREAD

**Issue by mertcansulupinar** [gsuitedevs/solutions#100]
Solution title: youtube-tracker

One sentence summary: Can't get videos' informations by videos' id

Description (1 - 2 paragraphs): When i run "markVideos" it says: TypeError: Cannot call method "split" of undefined. (satır: 90, dosya: "Code") 

How can i solve it ?

![image](https://user-images.githubusercontent.com/58821990/72091859-33d93900-3322-11ea-8210-af437fa641f3.png)

![image](https://user-images.githubusercontent.com/58821990/72091893-46ec0900-3322-11ea-8f6c-b56d95f90ed9.png)

**Comment by aliciawilliams** [comment]
To solve it, please change the value in cell A1 to "Video Link" (without the quotes). 

For future:
I've updated the template spreadsheet linked from this repo, and have requested an update to the README.md file to add the format instructions for the URLs that can be added in column A (the code only handles YouTube URLs starting with "www.youtube.com/watch?v=".

**Comment by mertcansulupinar** [comment]
Thank you so much it solved 👍
