### ISSUE TITLE
Use of the double quote (") character

### ISSUE THREAD

**Issue by Robin1824** [gsuitedevs/solutions#127]
I am using Mail Merge to send out Usernames and Passwords created for a project.

If the password contains the " character, it throws a JSON token error. 

Should I encapsulate the " character with double " ??

My workaround is to simply replace the " character with some other character, however this is very time consuming as it means that I have to manually go back to the accounts that Google created automatically and change the passwords before sending out. 

Your guidance will be appreciated.

**Comment by mhawksey** [comment]
@Robin1824 thanks for flagging this. I've added some code to this solution to escape cell data to make JSON safe. I've opened a pull request https://github.com/gsuitedevs/solutions/pull/130
