### ISSUE TITLE
Error : The starting column of the range is too small

### ISSUE THREAD

**Issue by vsugadev** [gsuitedevs/solutions#128]
Solution title:
The starting column of the range is too small
One sentence summary:
Unable to run the Mailmerge
![Capture](https://user-images.githubusercontent.com/20652424/80847245-eb010500-8bdc-11ea-9ace-3188f720c5a8.JPG)

Description (1 - 2 paragraphs):

Design Details:
Please provide a high level design overview with a motivation or problem statement to help us vet your idea.

Once a repo owner has approved this issue, you may use our template directory to make a pull
request for you solution. You may either submit the full implementation to this repo or if you
already have the implementation in another repo, simply link it in the README.

**Comment by stevestevestev** [comment]
you need an additional column: Email Sent
then the problem will go away

**Comment by vsugadev** [comment]
Working perfectly. Thanks
