### ISSUE TITLE
Mail Merger removes all line breaks (\n) in my draft email

### ISSUE THREAD

**Issue by www3cam** [gsuitedevs/solutions#129]
I try to create a draft email using your mail merge app and gmail.  However, when I send, it removes all line breaks.  The output looks like this: 

`Hi Cameron, This email doesn't have returns. Fen Cameron Fen Director of Research`

from:
```
Hi Cameron,

This email doesn't have returns.  Fen

Cameron Fen
Director of Research
```

**Comment by mhawksey** [comment]
@www3cam are you composing messages in plain text mode? The mail merge solution currently assumes the rich text editor is being used.

**Comment by sqrrrl** [comment]
Closing due to lack of response.

**Comment by github-account1111** [comment]
@sqrrrl could you reopen?
I have the same issue and I do use plaintext.
[Plaintext is important](https://useplaintext.email/).
