### ISSUE TITLE
Create a mail merge using Gmail and Google Sheets 

### ISSUE THREAD

**Issue by mhawksey** [gsuitedevs/solutions#54]
Solution title: Create a mail merge using Gmail and Google Sheets 

One sentence summary: Create and distribute visual rich mail merges from data in Google Sheets   

Description (1 - 2 paragraphs):
Simplify the process of producing visually rich mail merges using the Gmail composer and combining it with data from Google Sheets. With this solution you can automatically populate an email template created as a Gmail draft with data from Google Sheets. Merged emails are sent from your Gmail account allowing you to respond to recipient replies.   

Design Details:
Google Apps Script is perfect for automating repetitive tasks. Copy/pasting data from Google Sheets into an email can be error-prone, with fields potentially missed or data sent to the wrong recipient. You also want your emails to be visually appealing so that important information can be highlighted. At the same time you don't want to spend hours writing and formatting HTML markup and figuring how to include media like images and attachments. 

With this solution you can compose your email as a Gmail draft, using all the build-in features of the compose window to format your text, add images and other media. Once your draft is ready your template can automatically be populated with your data in Google Sheets and emailed to your recipients from your Gmail account. So that you can track emails this solution also records if and when your recipient was emailed.

**Comment by asrivas** [comment]
Sounds great! Approved. You can get started with our template directory: https://github.com/gsuitedevs/solutions/tree/master/template for your implementation

**Comment by asrivas** [comment]
Congratulations!
