### ISSUE TITLE
Record time and activities in the Calendar

### ISSUE THREAD

**Issue by duizendstra** [gsuitedevs/solutions#61]
Solution title: Record time and activities with Google Sheets, Calendar and Apps Script

One sentence summary: Record time in the calendar and synchronise the entries to a Google Spreadsheet.

Keeping a record of time spent on tasks can be a challenge. Should you update daily, weekly, make notes, use a spreadsheet or just a piece of paper? The dreaded monthly email, please enter your time, it is the end of the month and we need to send the invoices. 

This app enables you to write time in the calendar and synchronise it into Google Sheets for further processing.

Design Details:
Described in this article: https://medium.com/@duizendstra/record-time-and-activities-with-google-sheets-calendar-and-apps-script-41bf69244346

**Comment by sqrrrl** [comment]
Sounds good, approved :)

**Comment by asrivas** [comment]
Completed in #69 
https://developers.google.com/gsuite/solutions/calendar-timesheet
