### ISSUE TITLE
Automatically Create Draft Gmail Replies To Form Responses

### ISSUE THREAD

**Issue by benlcollins** [gsuitedevs/solutions#70]
Solution title: Automatically Create Draft Gmail Replies To Form Responses

One sentence summary: Use Apps Script to quickly create draft email replies to Google Form Responses.

Description (1 - 2 paragraphs): 
Quickly respond to large volumes of Form Responses by having Apps Script generate draft email replies ready for sending. The draft replies include the form responses, which can be reviewed inside the email. A generic thank you message is created and additional personal feedback can be added before hitting send.

Design Details:
Form submit trigger runs function that creates a draft email in Gmail with the Form Response data included.

**Comment by asrivas** [comment]
Sounds great! Approved. You can get started with our template directory: https://github.com/gsuitedevs/solutions/tree/master/template for your implementation

**Comment by asrivas** [comment]
Completed here:
https://github.com/gsuitedevs/solutions/tree/master/course-feedback-response
