### ISSUE TITLE
Generate Sales Report

### ISSUE THREAD

**Issue by aliciawilliams** [gsuitedevs/solutions#91]
Solution title: Generate Sales Report

One sentence summary: Bring sales data from your data warehouse directly into
 Google Sheets, and then automatically generate presentations 
 to summarize wins and opportunities for particular regions 
 and customers.

Description (1 - 2 paragraphs):

Annual and quarterly reports are a standard part of business 
for many enterprises. But automation can help eliminate the 
repetition inherent in these periodic obligations. 
If you find yourself needing to analyze and present findings 
from large sets of stored data, consider using automation 
to help streamline your reporting. 

This solution creates a tool that connects to sales data in 
BigQuery, an analytics data warehouse, from directly within 
Google Sheets. A configuration sheet allows a user to provide 
parameters for the report, such as the Account Name and 
Region. With the click of a button, a customized report
with the latest sales data is automatically created in just 
a matter of seconds! 

Design Details:
A configuration tab in a Google Sheet lets a user pick an Account Name and Region. Then these values become parameters in a BigQuery query that is connected to another tab via the Data Connector. Once the data is refreshed, an Apps Script creates a Google Slides document based off of a template that includes data for that Account Name and Region.

Once a repo owner has approved this issue, you may use our template directory to make a pull
request for you solution. You may either submit the full implementation to this repo or if you
already have the implementation in another repo, simply link it in the README.

**Comment by asrivas** [comment]
Approved! Here is the template:
https://github.com/gsuitedevs/solutions/tree/master/template

**Comment by asrivas** [comment]
Completed in #90
