### ISSUE TITLE
Null error when sending emails without variable tags in Mail Merge

### ISSUE THREAD

**Issue by jackboyce** [gsuitedevs/solutions#98]
Solution title:
Null error when sending emails without variable tags

One sentence summary:
Programs throws a null error when you try to use a draft without {{}} tags.

Solution:
Add this one-liner to line 145: if(templateVars == null) return JSON.parse(template);

**Comment by asrivas** [comment]
@mhawksey can you take a look?

**Comment by mhawksey** [comment]
@asrivas sure - I'll test the suggested fix and open a pull request if it's ok.
