### ISSUE TITLE
Mail Merge solution only support Unicode 5.1 with GmailApp

### ISSUE THREAD

**Issue by mhawksey** [gsuitedevs/solutions#99]
In the Mail Merge solution a known limitation of [`GmailApp` is support for Unicode characters](https://stackoverflow.com/a/50883782/1027723). This means Gmail drafts with emojis like '☺' are replaced with ������. 

A quick solution would be to replace `GmailApp.sendEmail()` with `MailApp.sendEmail()` [here](https://github.com/gsuitedevs/solutions/blob/6358e0e321eb80f6b5f30fa232e100bca66de68a/mail-merge/src/Code.js#L83).

Downside of this approach is it's an extra scope.

**Comment by emddom** [comment]
The mail merge script replaces the {{...}} fields only in the mail subject, not in the mail body.
In the body  the original {{field}} seems to be replaced with an empty string.

**Comment by mhawksey** [comment]
@emddom I'm not able to replicate this issue. As this is unrelated to unicode support it would be better to open this as a new issue ticket and provide some more details of your draft message and sheet data

**Comment by mhawksey** [comment]
Picked up in [latest version release notes](https://mashe.hawksey.info/2020/04/a-bulk-email-mail-merge-with-gmail-and-google-sheets-solution-evolution-using-v8/)
